title:          Fatwas of Ibn Baz
baseurl:        "/binbaz"
url:            "https://alsalafiyyah.github.io"
author:
  name:         Instagram@Alsalafiyyah
  email:        alsalafiyyah@icloud.com
encoding:         UTF-8
github: [metadata]
timezone: Asia/Riyadh
permalink: /:title
paginate:       20
paginate_path: "/fatwas/:num/"
markdown:       kramdown
remote_theme:  creativetimofficial/material-kit
